# Generated by Django 4.1.4 on 2022-12-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_temperaturesensordata_sensor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturesensordata',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
